name: RankPlaceHolders
version: '${project.version}'
main: net.playerrs.RankPlaceHolders
api-version: '1.20'
depend: [PlaceholderAPI]
commands:
    setpremiumlevel:
        description: Set the premium level for a player
        permission: rankplaceholders.setpremiumlevel
        aliases:
            - setplevel
    nextlevel:
        description: Set the next level for a player
        permission: rankplaceholders.nextlevel
    unlockquest:
        description: Unlock a quest
        permission: rankplaceholders.unlockquest